config/routes.rb
Rails.application.routes.draw do

  resources :entries do
    collection do
      get :archived
    end
  end

  root to: redirect("/entries")

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :term, presence: true

  scope :existing, ->{ where(archived: false) }
  scope :archived, ->{ where(archived: true) }

  default_scope -> { order(term: :asc) }

  def archive!
    update_attributes!(archived: true)
  end

  def full_term
    expanded_term.present? ? expanded_term : term
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
  end

  def archived
    @entries = Entry.archived
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)

    if entry.save
      flash.notice = 'Entry created'
      redirect_to entry_path(entry)
    else
      render action: :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if entry.update_attributes(entry_params)
      flash.notice = 'Entry saved'
      redirect_to entry_path(entry)
    else
      render action: :new
    end
  end

  def destroy
    entry.archive!

    flash.notice = 'Entry sent to trash'
    redirect_to entries_path
  end

private
  def entry
    @entry ||= Entry.find(params[:id])
  end
  helper_method :entry

  def presented_entry
    EntryPresenter.new(entry)
  end
  helper_method :presented_entry

  def entries
    @entries ||= Entry.existing
  end
  helper_method :entries

  def entry_params
    params.require(:entry).permit(:term, :definition, :expanded_term)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<li>
  <h3>
    <%= link_to entry_path(entry) do %>
      <% if entry.expanded_term.present? %>
        <%= entry.expanded_term %>
        <span class="acronym">(<%= entry.term %>)</span>
      <% else %>
        <%= entry.term %>
      <% end %>

      <% if entry.definition.blank? %>
        <span class="no-definition">No definition</span>
      <% end %>
    <% end %>
  </h3>
</li>

app/views/entries/_form.html.erb
<%= semantic_form_for entry do |f| %>

  <%= f.inputs do %>
    <%= f.input :term %>
    <%= f.input :expanded_term %>
    <%= f.input :definition, input_html: { rows: 5 } %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, button_html: {
                            class: 'btn btn-primary',
                          } %>
    <%= f.action :cancel, as: :link %>
  <% end %>

<% end %>

app/views/entries/archived.html.erb
<h1>Archived entries</h1>

<% if entries.any? %>
  <ul class="entries">
    <%= render partial: 'entry', collection: entries %>
  </ul>
<% else %>
  <p>There are no archived entries yet.</p>
<% end %>

<p class="archived"><%= link_to "View all entries", entries_path %></p>

app/views/entries/edit.html.erb
<h1>Edit entry</h1>

<%= render partial: 'form' %>

app/views/entries/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Entries</h1>
  </div>
  <div class="col-md-6 actions">
    <p><%= link_to "Add new entry", new_entry_path, class: 'btn btn-success' %></p>
  </div>
</div>

<% if entries.any? %>
  <ul class="entries">
    <%= render partial: 'entry', collection: entries %>
  </ul>
<% else %>
  <p>There are no entries yet. <%= link_to "Add one", new_entry_path %>.</p>
<% end %>

<p class="archived">
  <%= link_to "View archived entries", archived_entries_path %>
</p>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render partial: 'form' %>

app/views/entries/show.html.erb
<h1>
  <% if entry.expanded_term.present? %>
    <%= entry.expanded_term %>
    <span class="acronym">(<%= entry.term %>)</span>
  <% else %>
    <%= entry.term %>
  <% end %>

  <% if entry.archived? %>
    <span class="label label-danger">Archived</span>
  <% end %>
</h1>

<div class="definition">
  <% if entry.definition.present? %>
    <%= simple_format presented_entry.definition_with_links %>
  <% else %>
    <p class="no-definition">
      There's no definition for this term yet.
      <% unless entry.archived? %>
        You can <%= link_to "add it", edit_entry_path(entry) %>.
      <% end %>
    </p>
  <% end %>
</div>


<div class="single-actions">
  <% unless entry.archived? %>
    <%= link_to "Edit this entry", edit_entry_path(entry) %>
    <%= link_to "Archive this entry", entry_path(entry), method: :delete,
                                                         class: 'delete',
                                                         data: {
                                                           confirm: "Are you sure? This can't be undone."
                                                         } %>
  <% end %>

  <span class="last-update">Last updated <%= entry.updated_at.strftime("%-d %b %Y, %-I:%M%P") %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glossary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <h1><%= link_to "One Government at the Border: Glossary", root_path %></h1>
  </header>

  <main>
    <%= yield %>
  </main>

</body>
</html>